
auth.token=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

defaults.org=chefu-technologies
defaults.project=sudoku

defaults.url=https://sentry.io/
